# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3nvG9DxVSAczy3F0Qj7tKoLsyZ1uX6A
"""

checkerboard = [

[1, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 1, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0]

]
a = input().split()
b = input().split()
x1, y1 = int(a[0]), int(a[1])
x2, y2 = int(b[0]), int(b[1])

if x1 == x2 and y1 == y2:
    print("No")
elif checkerboard[x2][y2] == 1:
    print("No")
else:
    if abs(x1 - x2) <= 1 and abs(y1 - y2) <= 1:
        print("Yes")
    else:
        print("No")